/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Vote = {
  _id: string;
  _type: "vote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  voteType?: "upvote" | "downvote";
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  comment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  createdAt?: string;
};

export type Comment = {
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  parentComment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  isReported?: boolean;
  createdAt?: string;
  isDeleted?: boolean;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  originalTitle?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  subreadit?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subreadit";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  isReported?: boolean;
  publishedAt?: string;
  isDeleted?: boolean;
};

export type Subreadit = {
  _id: string;
  _type: "subreadit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  moderator?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  createdAt?: string;
};

export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  username?: string;
  email?: string;
  imageUrl?: string;
  joinedAt?: string;
  isReported?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Vote | Comment | Post | Subreadit | User | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/comment/getCommentById.ts
// Variable: getCommentByIdQuery
// Query: *[_type == "comment" && _id == $commentId][0]{        _id,        content,        createdAt,        "author":author->,        isDeleted        }
export type GetCommentByIdQueryResult = {
  _id: string;
  content: string | null;
  createdAt: string | null;
  author: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: string;
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  isDeleted: boolean | null;
} | null;

// Source: ./sanity/lib/comment/getCommentReplies.ts
// Variable: getCommentRepliesQuery
// Query: *[_type == "comment" && parentComment._ref == $commentId] {        ...,        _id,        content,        createdAt,        "author": author->,        "replies": *[_type == "comment" && parentComment._ref == ^._id],        "votes": {            "upvotes": count(*[_type == "vote" && comment._ref == ^._id && voteType == "upvote"]),            "downvotes": count(*[_type == "vote" && comment._ref == ^._id && voteType == "downvote"]),            "netScore": count(*[_type == "vote" && comment._ref == ^._id && voteType == "upvote"]) - count(*[_type == "vote" && comment._ref == ^._id && voteType == "downvote"]),            "voteStatus": *[_type == "vote" && comment._ref == ^._id && user._ref == $userId][0].voteType,        },      } | order(votes.netScore desc) //votes.netScore desc -> if you want to sort by net score
export type GetCommentRepliesQueryResult = Array<{
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content: string | null;
  author: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: string;
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  parentComment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  isReported?: boolean;
  createdAt: string | null;
  isDeleted?: boolean;
  replies: Array<{
    _id: string;
    _type: "comment";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    content?: string;
    author?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "user";
    };
    post?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "post";
    };
    parentComment?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "comment";
    };
    isReported?: boolean;
    createdAt?: string;
    isDeleted?: boolean;
  }>;
  votes: {
    upvotes: number;
    downvotes: number;
    netScore: number;
    voteStatus: "downvote" | "upvote" | null;
  };
}>;

// Source: ./sanity/lib/post/getPosts.ts
// Variable: getAllPostsQuery
// Query: *[_type == "post" && isDeleted != true] {    _id,    title,    "slug": slug.current,    body,    publishedAt,    "author": author->    ,    "subreadit": subreadit->,    image,    isDeleted  } | order(publishedAt desc)
export type GetAllPostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  publishedAt: string | null;
  author: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: string;
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  subreadit: {
    _id: string;
    _type: "subreadit";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    description?: string;
    slug?: Slug;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    moderator?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "user";
    };
    createdAt?: string;
  } | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  isDeleted: boolean | null;
}>;

// Source: ./sanity/lib/post/getPostsById.ts
// Variable: getPostByIdQuery
// Query: *[_type == "post" && _id == $postId]{        _id,        title,        "slug":slug.current,        body,        publishedAt,        "author":author->,        "subreadit":subreadit->,        image,        isDeleted        }[0]
export type GetPostByIdQueryResult = {
  _id: string;
  title: string | null;
  slug: null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  publishedAt: string | null;
  author: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: string;
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  subreadit: {
    _id: string;
    _type: "subreadit";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    description?: string;
    slug?: Slug;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    moderator?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "user";
    };
    createdAt?: string;
  } | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  isDeleted: boolean | null;
} | null;

// Source: ./sanity/lib/subreadits/creatSubreadit.ts
// Variable: checkingExistingQuery
// Query: *[_type == "subreadit" && title == $name][0]{_id}
export type CheckingExistingQueryResult = {
  _id: string;
} | null;
// Variable: checkSlugQuery
// Query: *[_type == "subreadit" && slug.current == $slug][0]{                _id            }
export type CheckSlugQueryResult = {
  _id: string;
} | null;

// Source: ./sanity/lib/subreadits/getPostsforsubreadit.ts
// Variable: getPostsforsubreaditQuery
// Query: *[_type == "post" && subreadit._ref == $id]{        ...,        "slug":slug.current,        "author":author->,        "subreadit":subreadit->,        "category":category->,        "upvotes": count(*[_type == "vote" && post._ref == ^._id && voteType == "upvote"]),        "downvotes": count(*[_type == "vote" && post._ref == ^._id && voteType == "downvote"]),        "netScore" : count(*[_type == "vote" && post._ref == ^._id && voteType == "upvote"]) - count(*[_type == "vote" && post._ref == ^._id && voteType == "downvote"]),        "commentCount" : count(*[type == "comment" && post._ref == ^._id])        } | order(publishedAt desc)
export type GetPostsforsubreaditQueryResult = Array<{
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  originalTitle?: string;
  author: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: string;
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  subreadit: {
    _id: string;
    _type: "subreadit";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    description?: string;
    slug?: Slug;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    moderator?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "user";
    };
    createdAt?: string;
  } | null;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  isReported?: boolean;
  publishedAt?: string;
  isDeleted?: boolean;
  slug: null;
  category: null;
  upvotes: number;
  downvotes: number;
  netScore: number;
  commentCount: number;
}>;

// Source: ./sanity/lib/subreadits/getSubreaditbySlug.ts
// Variable: getsubreaditbySlugQuery
// Query: *[_type == "subreadit" && slug.current == $slug][0]{        ...,        "slug":slug.current,        "moderator":moderator->,                }
export type GetsubreaditbySlugQueryResult = {
  _id: string;
  _type: "subreadit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug: string | null;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  moderator: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: string;
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  createdAt?: string;
} | null;

// Source: ./sanity/lib/subreadits/getSubreadits.ts
// Variable: getSubreaditsQuery
// Query: *[_type == "subreadit"] {        ...,        "slug": slug.current,        "moderator": moderator->,      } | order(createdAt desc)
export type GetSubreaditsQueryResult = Array<{
  _id: string;
  _type: "subreadit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug: string | null;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  moderator: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: string;
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  createdAt?: string;
}>;

// Source: ./sanity/lib/subreadits/searchSubreadits.ts
// Variable: searchSubreaditQuery
// Query: *[_type =="subreadit" && title match $searchTerms + "*"]{        _id,        title,        "slug":slug.current,        description,        image,        "moderator":moderator->,        createdAt        } | order(createdAt desc)
export type SearchSubreaditQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  moderator: {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    username?: string;
    email?: string;
    imageUrl?: string;
    joinedAt?: string;
    isReported?: boolean;
  } | null;
  createdAt: string | null;
}>;

// Source: ./sanity/lib/user/getUser.ts
// Variable: getExistingUserQuery
// Query: *[_type == "user" && _id == $id][0]
export type GetExistingUserQueryResult = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  username?: string;
  email?: string;
  imageUrl?: string;
  joinedAt?: string;
  isReported?: boolean;
} | null;

// Source: ./sanity/lib/vote/downVotePost.ts
// Variable: existingVoteDownVoteQuery
// Query: *[_type =="vote" && post._ref == $postId && user._ref == $userId][0]
export type ExistingVoteDownVoteQueryResult = {
  _id: string;
  _type: "vote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  voteType?: "downvote" | "upvote";
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  comment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  createdAt?: string;
} | null;

// Source: ./sanity/lib/vote/downvoteComment.ts
// Variable: existingVoteDownvoteCommentQuery
// Query: *[_type == "vote" && comment._ref == $commentId && user._ref == $userId][0]
export type ExistingVoteDownvoteCommentQueryResult = {
  _id: string;
  _type: "vote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  voteType?: "downvote" | "upvote";
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  comment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  createdAt?: string;
} | null;

// Source: ./sanity/lib/vote/getPostComments.ts
// Variable: getPostCommentsQuery
// Query: *[_type == "comment" && post._ref == $postId && !defined(parentComment)] | order(_createdAt desc) {      _id,      content,      createdAt,      "author": author->{        _id,        username,        imageUrl      },      "replies": *[_type == "comment" && parentComment._ref == ^._id] | order(_createdAt asc) {        _id,        content,        createdAt,        "author": author->{          _id,          username,          imageUrl        },        "votes": {          "upvotes": count(*[_type == "vote" && comment._ref == ^._id && voteType == "upvote"]),          "downvotes": count(*[_type == "vote" && comment._ref == ^._id && voteType == "downvote"]),          "netScore": count(*[_type == "vote" && comment._ref == ^._id && voteType == "upvote"]) - count(*[_type == "vote" && comment._ref == ^._id && voteType == "downvote"]),          "voteStatus": *[_type == "vote" && comment._ref == ^._id && user._ref == $userId][0].voteType        }      },      "votes": {        "upvotes": count(*[_type == "vote" && comment._ref == ^._id && voteType == "upvote"]),        "downvotes": count(*[_type == "vote" && comment._ref == ^._id && voteType == "downvote"]),        "netScore": count(*[_type == "vote" && comment._ref == ^._id && voteType == "upvote"]) - count(*[_type == "vote" && comment._ref == ^._id && voteType == "downvote"]),        "voteStatus": *[_type == "vote" && comment._ref == ^._id && user._ref == $userId][0].voteType      }    }
export type GetPostCommentsQueryResult = Array<{
  _id: string;
  content: string | null;
  createdAt: string | null;
  author: {
    _id: string;
    username: string | null;
    imageUrl: string | null;
  } | null;
  replies: Array<{
    _id: string;
    content: string | null;
    createdAt: string | null;
    author: {
      _id: string;
      username: string | null;
      imageUrl: string | null;
    } | null;
    votes: {
      upvotes: number;
      downvotes: number;
      netScore: number;
      voteStatus: "downvote" | "upvote" | null;
    };
  }>;
  votes: {
    upvotes: number;
    downvotes: number;
    netScore: number;
    voteStatus: "downvote" | "upvote" | null;
  };
}>;

// Source: ./sanity/lib/vote/getPostVoteStatus.ts
// Variable: getPostVoteStatusQuery
// Query: *[_type == "vote" && post._ref == $postId && user._ref == $userId][0].voteType
export type GetPostVoteStatusQueryResult = "downvote" | "upvote" | null;

// Source: ./sanity/lib/vote/getPostVotes.ts
// Variable: getPostVotesQuery
// Query: {        "upvotes":count(*[_type=="vote" && post._ref == $postId && voteType == "upvote"]),        "downvotes":count(*[_type == "vote" && post._ref == $postId && upvote ==        "downvote"]),        "netScore":count(*[_type=="vote" && post._ref == $postId && voteType ==        "upvote"]) - count(*[_type == "vote" && post._ref == $postId && upvote ==        "downvote"])          }
export type GetPostVotesQueryResult = {
  upvotes: number;
  downvotes: number;
  netScore: number;
};

// Source: ./sanity/lib/vote/getUserPostVote.ts
// Variable: getUserPostVoteQuery
// Query: *[_type == "vote" && post._ref == $postId && user._ref == $userId][0].voteType
export type GetUserPostVoteQueryResult = "downvote" | "upvote" | null;

// Source: ./sanity/lib/vote/upvoteComment.ts
// Variable: exisitingVoteUpvoteCommentQuery
// Query: *[_type =="vote" && comment._ref == $commentId && user._ref == $userId][0]
export type ExisitingVoteUpvoteCommentQueryResult = {
  _id: string;
  _type: "vote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  voteType?: "downvote" | "upvote";
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  comment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  createdAt?: string;
} | null;

// Source: ./sanity/lib/vote/upvotePost.ts
// Variable: exisitingVoteUpvoteQuery
// Query: *[_type == "vote" && post._ref == $postId && user._ref == $userId][0]
export type ExisitingVoteUpvoteQueryResult = {
  _id: string;
  _type: "vote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  voteType?: "downvote" | "upvote";
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  comment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  createdAt?: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n        *[_type == \"comment\" && _id == $commentId][0]{\n        _id,\n        content,\n        createdAt,\n        \"author\":author->,\n        isDeleted\n        }\n        ": GetCommentByIdQueryResult;
    "\n      *[_type == \"comment\" && parentComment._ref == $commentId] {\n        ...,\n        _id,\n        content,\n        createdAt,\n        \"author\": author->,\n        \"replies\": *[_type == \"comment\" && parentComment._ref == ^._id],\n        \"votes\": {\n            \"upvotes\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"upvote\"]),\n            \"downvotes\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"downvote\"]),\n            \"netScore\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"upvote\"]) - count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"downvote\"]),\n            \"voteStatus\": *[_type == \"vote\" && comment._ref == ^._id && user._ref == $userId][0].voteType,\n        },\n      } | order(votes.netScore desc) //votes.netScore desc -> if you want to sort by net score\n    ": GetCommentRepliesQueryResult;
    "*[_type == \"post\" && isDeleted != true] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    body,\n    publishedAt,\n    \"author\": author->\n    ,\n    \"subreadit\": subreadit->,\n    image,\n    isDeleted\n  } | order(publishedAt desc)": GetAllPostsQueryResult;
    "\n        *[_type == \"post\" && _id == $postId]{\n        _id,\n        title,\n        \"slug\":slug.current,\n        body,\n        publishedAt,\n        \"author\":author->,\n        \"subreadit\":subreadit->,\n        image,\n        isDeleted\n        }[0]": GetPostByIdQueryResult;
    "*[_type == \"subreadit\" && title == $name][0]{_id}": CheckingExistingQueryResult;
    "\n                *[_type == \"subreadit\" && slug.current == $slug][0]{\n                _id\n            }\n        ": CheckSlugQueryResult;
    "\n        *[_type == \"post\" && subreadit._ref == $id]{\n        ...,\n        \"slug\":slug.current,\n        \"author\":author->,\n        \"subreadit\":subreadit->,\n        \"category\":category->,\n        \"upvotes\": count(*[_type == \"vote\" && post._ref == ^._id && voteType == \"upvote\"]),\n\n        \"downvotes\": count(*[_type == \"vote\" && post._ref == ^._id && voteType == \"downvote\"]),\n\n        \"netScore\" : count(*[_type == \"vote\" && post._ref == ^._id && voteType == \"upvote\"]) - count(*[_type == \"vote\" && post._ref == ^._id && voteType == \"downvote\"]),\n\n        \"commentCount\" : count(*[type == \"comment\" && post._ref == ^._id])\n        } | order(publishedAt desc)\n        ": GetPostsforsubreaditQueryResult;
    "\n        *[_type == \"subreadit\" && slug.current == $slug][0]{\n        ...,\n        \"slug\":slug.current,\n        \"moderator\":moderator->,\n        \n        } ": GetsubreaditbySlugQueryResult;
    "*[_type == \"subreadit\"] {\n        ...,\n        \"slug\": slug.current,\n        \"moderator\": moderator->,\n      } | order(createdAt desc)": GetSubreaditsQueryResult;
    "\n        *[_type ==\"subreadit\" && title match $searchTerms + \"*\"]{\n        _id,\n        title,\n        \"slug\":slug.current,\n        description,\n        image,\n        \"moderator\":moderator->,\n        createdAt\n        } | order(createdAt desc)\n        ": SearchSubreaditQueryResult;
    "*[_type == \"user\" && _id == $id][0]": GetExistingUserQueryResult;
    "\n        *[_type ==\"vote\" && post._ref == $postId && user._ref == $userId][0]\n        ": ExistingVoteDownVoteQueryResult;
    "\n        *[_type == \"vote\" && comment._ref == $commentId && user._ref == $userId][0]\n        ": ExistingVoteDownvoteCommentQueryResult;
    "\n    *[_type == \"comment\" && post._ref == $postId && !defined(parentComment)] | order(_createdAt desc) {\n      _id,\n      content,\n      createdAt,\n      \"author\": author->{\n        _id,\n        username,\n        imageUrl\n      },\n      \"replies\": *[_type == \"comment\" && parentComment._ref == ^._id] | order(_createdAt asc) {\n        _id,\n        content,\n        createdAt,\n        \"author\": author->{\n          _id,\n          username,\n          imageUrl\n        },\n        \"votes\": {\n          \"upvotes\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"upvote\"]),\n          \"downvotes\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"downvote\"]),\n          \"netScore\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"upvote\"]) - count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"downvote\"]),\n          \"voteStatus\": *[_type == \"vote\" && comment._ref == ^._id && user._ref == $userId][0].voteType\n        }\n      },\n      \"votes\": {\n        \"upvotes\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"upvote\"]),\n        \"downvotes\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"downvote\"]),\n        \"netScore\": count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"upvote\"]) - count(*[_type == \"vote\" && comment._ref == ^._id && voteType == \"downvote\"]),\n        \"voteStatus\": *[_type == \"vote\" && comment._ref == ^._id && user._ref == $userId][0].voteType\n      }\n    }\n  ": GetPostCommentsQueryResult;
    "*[_type == \"vote\" && post._ref == $postId && user._ref == $userId][0].voteType": GetPostVoteStatusQueryResult | GetUserPostVoteQueryResult;
    "\n        {\n        \"upvotes\":count(*[_type==\"vote\" && post._ref == $postId && voteType == \"upvote\"]),\n\n        \"downvotes\":count(*[_type == \"vote\" && post._ref == $postId && upvote ==\n        \"downvote\"]),\n\n        \"netScore\":count(*[_type==\"vote\" && post._ref == $postId && voteType ==\n        \"upvote\"]) - count(*[_type == \"vote\" && post._ref == $postId && upvote ==\n        \"downvote\"])  \n        }": GetPostVotesQueryResult;
    "\n        *[_type ==\"vote\" && comment._ref == $commentId && user._ref == $userId][0]\n        ": ExisitingVoteUpvoteCommentQueryResult;
    "\n        *[_type == \"vote\" && post._ref == $postId && user._ref == $userId][0]\n        \n        ": ExisitingVoteUpvoteQueryResult;
  }
}
